language: node_js
node_js:
  - "12"
after_success:
- ./bin/codecov -e TRAVIS_NODE_VERSION
install:
  - npm install -g mocha
  - npm install -g codecov
  - npm install -g istanbul
  - npm install
  - npm run coverage