language: node_js
node_js:
  - "12"
after_success:
- ./bin/codecov -e TRAVIS_NODE_VERSION
install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g npm-run-all
  - npm install
  - npm run test
  - npm run build
  - npm run after-30-days